In [1]:
import numpy as np
import sys
sys.path
sys.path.append('./dave/diffimg/')
import tessprf
pathToMatFile = './data/prf/'
obj = tessprf.TessPrf(pathToMatFile)
obj.getPrfAtColRow(123.0, 456.0, 1,1,1)

col 123.0
cr (2,) float64
evalCol (25,) int64
evalColrow (25, 2) int64
evalRow (25,) int64
nEval 5
prfObj (25,) object
row 456.0
self <tessprf.TessPrf object at 0x10cc77e90>
srt (25,) int64


array([[2.53075469e-05, 2.61737941e-05, 2.23910058e-05, 1.94908173e-05,
        2.83417993e-05, 3.11626884e-05, 3.13278231e-05, 3.19630054e-05,
        3.09809911e-05, 2.81038318e-05, 2.36466019e-05, 2.04141008e-05,
        2.29575178e-05],
       [2.42706428e-05, 2.40807668e-05, 1.89780044e-05, 1.94177167e-05,
        2.32406685e-05, 2.17086183e-05, 2.78028492e-05, 2.32212629e-05,
        2.14542511e-05, 2.08314514e-05, 2.11056088e-05, 2.10222983e-05,
        2.49968856e-05],
       [2.86030811e-05, 2.77606084e-05, 5.38267929e-05, 3.03578012e-05,
        2.08170594e-05, 2.65322164e-05, 1.93241509e-05, 4.79847743e-05,
        5.72757175e-05, 4.41179337e-05, 3.12803227e-05, 2.53950178e-05,
        2.63381001e-05],
       [2.30549629e-05, 2.32818883e-05, 9.57862986e-05, 2.41463509e-04,
        1.46556128e-04, 1.20257778e-04, 1.46756011e-04, 1.58979383e-04,
        1.35470851e-04, 9.02326481e-05, 4.94072059e-05, 2.58857480e-05,
        2.28613805e-05],
       [2.87257244e-05, 2.03804056e-

In [2]:
import scipy.io as spio
import os
fn = "tess2018243163600-00072_035-%i-%i-characterized-prf.mat" %(1, 1)
path = os.path.join('./data/prf/', fn)

obj = spio.matlab.loadmat(path, struct_as_record=False, squeeze_me=True)

In [3]:
obj

{'__globals__': [],
 '__header__': 'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Wed Aug 29 23:51:55 2018',
 '__version__': '1.0',
 'prfStruct': array([<scipy.io.matlab.mio5_params.mat_struct object at 0x10297c6d0>,
       dtype=object)}

In [4]:
prfObj = obj['prfStruct']
prfObj

array([<scipy.io.matlab.mio5_params.mat_struct object at 0x10297c6d0>,
      dtype=object)

In [22]:
beep[0]

<function __main__.<lambda>>

In [25]:
npmap = lambda f, x: np.array(list(map(f, x)))

def badmap(f,x):
    return np.array(map(f, x))

In [15]:
badmap(x.ccdColumn,prfObj)

NameError: name 'x' is not defined

In [19]:
beep = lambda x: x.ccdColumn, prfObj

(<function __main__.<lambda>>,
 array([<scipy.io.matlab.mio5_params.mat_struct object at 0x10297c6d0>,
       dtype=object))

In [24]:
badmap(beep[0],beep[1])

array([  45,   45, 1069, 1069, 1069, 1069, 1069, 1580, 1580, 1580, 1580,
       1580,   45, 2092, 2092, 2092, 2092, 2092,   45,   45,  557,  557,
        557,  557,  557])

In [23]:
npmap(beep[0],beep[1])

array([  45,   45, 1069, 1069, 1069, 1069, 1069, 1580, 1580, 1580, 1580,
       1580,   45, 2092, 2092, 2092, 2092, 2092,   45,   45,  557,  557,
        557,  557,  557])

In [26]:
evalCol = npmap(lambda x: x.ccdColumn, prfObj)
evalRow = npmap(lambda x: x.ccdRow, prfObj)

#Sort prfArray so its the right shape for getBracketingIndices()
nEval = np.sqrt(len(prfObj))
nEval = int(nEval)

In [13]:
npmap

<function __main__.<lambda>>

In [27]:
evalColrow = np.vstack((evalCol, evalRow)).transpose()
srt = np.lexsort((evalRow, evalCol))

In [28]:
evalColrow[srt]

array([[  45,    1],
       [  45,  513],
       [  45, 1025],
       [  45, 1536],
       [  45, 2048],
       [ 557,    1],
       [ 557,  513],
       [ 557, 1025],
       [ 557, 1536],
       [ 557, 2048],
       [1069,    1],
       [1069,  513],
       [1069, 1025],
       [1069, 1536],
       [1069, 2048],
       [1580,    1],
       [1580,  513],
       [1580, 1025],
       [1580, 1536],
       [1580, 2048],
       [2092,    1],
       [2092,  513],
       [2092, 1025],
       [2092, 1536],
       [2092, 2048]])

In [ ]:
evalColRow = evalColrow[srt].reshape((nEval, nEval, 2))